### ISSUE TITLE
Dependency cycle: MarginState <-> MarginCommon

### ISSUE THREAD

**Issue by jurglic** [dydxprotocol/protocol_v1#489]
I've tried preparing source for `Margin` contract that is missing on Etherscan... However the source flattener (truffle-flattener) fails because there's a dependency cycle between `MarginCommon` and `MarginState` libraries, as both require each other. 

Perhaps `MarginState` could be collapsed into higher level `MarginCommon` library? Only couple contracts require `MarginState` without `MarginCommon`...

**Comment by BrendanChou** [comment]
I solved this by removing the line
`import { MarginCommon } from "./MarginCommon.sol";`
from `MarginState.sol`
Before doing flattening

**Comment by jurglic** [comment]
I've tried it, but it breaks the build process because `MarginState` references `MarginCommon.Position`...

**Comment by BrendanChou** [comment]
Yeah, I guess I think of flattening as a one-off kind of thing, so this is a temporary change you can do one time when flattening
